# Metadata for the plugin
plugin:
    # Global plugin attributes
    type: unknown                   # plugin type (gateway, interface, protocol, system, web)
    description:
        de: 'Beispiel Plugin mit MQTT Protokoll Nutzung für SmartHomeNG v1.7 und höher'
        en: 'Sample plugin using MQTT protocol for SmartHomeNG v1.7 and up'
    maintainer: msinn
#    tester:                         # Who tests this plugin?
    state: develop                  # change to ready when done with development
#    keywords: iot xyz
#    documentation: https://github.com/smarthomeNG/smarthome/wiki/CLI-Plugin        # url of documentation (wiki) page
#    support: https://knx-user-forum.de/forum/supportforen/smarthome-py

    version: 1.7.0                  # Plugin version
    sh_minversion: 1.7              # minimum shNG version to use this plugin
#    sh_maxversion:                 # maximum shNG version to use this plugin (leave empty if latest)
#    py_minversion: 3.6             # minimum Python version to use for this plugin
#    py_maxversion:                 # maximum Python version to use for this plugin (leave empty if latest)
    multi_instance: False           # plugin supports multi instance
    restartable: unknown
    classname: SamplePlugin         # class containing the plugin

parameters:
    # Definition of parameters to be configured in etc/plugin.yaml (enter 'parameters: NONE', if section should be empty)

item_attributes:
    # Definition of item attributes defined by this plugin (enter 'item_attributes: NONE', if section should be empty)

item_structs:
    # Definition of item-structure templates for this plugin (enter 'item_structs: NONE', if section should be empty)

plugin_functions:
    # Definition of plugin functions defined by this plugin (enter 'plugin_functions: NONE', if section should be empty)

logic_parameters:
    # Definition of logic parameters defined by this plugin (enter 'logic_parameters: NONE', if section should be empty)

